### ISSUE TITLE
Compare our projects

### ISSUE THREAD

**Issue by skychik** [skychik/for-programming#2]
Запуль свою директорию Lab2.Sasha, чтоб я смог посмотреть, отличаются ли они. И отпишись тут, если прочитала

**Comment by AlphaBeth** [comment]
Открытые проблемы (issues) принято закрывать после их решения. В github предусмотрена такая функциональность.

**Comment by skychik** [comment]
Проблема еще не решена

**Comment by skychik** [comment]
Done

**Comment by skychik** [comment]
Решено после мержа with-Anonimus-class
