### ISSUE TITLE
JUnit тесты находятся в неправильном каталоге

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#23]
Как я вижу, вы начали использовать JUnit тесты. Это хорошо. Вот только структура проекта у вас неправильная.
Тесты должны быть в каталоге src/test/java/...

**Comment by skychik** [comment]
done

**Comment by skychik** [comment]
после их перемещения тесты как будто бы перестали видеть сторонние библиотеки и, собственно, перестали работать

**Comment by AlphaBeth** [comment]
Какие именно?
И хотелось бы увидеть структуру проекта.

**Comment by skychik** [comment]
ну, вообще был только один тест

**Comment by skychik** [comment]
![image](https://cloud.githubusercontent.com/assets/25961004/24588363/67c057a6-17cf-11e7-9082-0905ef141ad2.png)

**Comment by AlphaBeth** [comment]
Это проблемы IDE. Правой кнопкой по каталогу test в окне проекта -> Mark Directory as... -> Test Sources Root

**Comment by AlphaBeth** [comment]
Не по test, а по test/java

**Comment by skychik** [comment]
eeee, заработало
