### ISSUE TITLE
add и show

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#24]
Только заметил, что в вашем варианте предусмотрено только удаление из коллекции. Потому попрошу дополнительно реализовать следующие команды:
1. `add {element}` - принимает в качестве аргумента csv строку и добавляет ее в коллекцию. 
2. show - выводит текущее содержимое коллекции в формате csv.

**Comment by skychik** [comment]
ok

**Comment by skychik** [comment]
добавлены
