### ISSUE TITLE
Ненужные файлы в репозитории

### ISSUE THREAD

**Issue by AlphaBeth** [skychik/for-programming#5]
Репозиторий содержит скомпилированные .class файлы в каталогах build и out.

В репозитории должны храниться только значимые артефакты проекта: исходный код, документация, файлы конфигурации, скрипты сборки, возможно конфигурационные файлы используемой среды разработки (каталог .idea, например).

Вариант решения: удаление ненужных файлов и каталогов командой git rm, последующее добавление .class файлов в [.gitignore](https://git-scm.com/docs/gitignore).
Для удаления этих файлов во всех коммитах можно использовать [filter-branch](https://git-scm.com/docs/git-filter-branch), например так (на свой страх и риск)
`git filter-branch --tree-filter 'rm -rf Laba2.Sasha/out/ Laba2.Sasha/build'`

**Comment by skychik** [comment]
А зачем вообще нужны эти папки?

**Comment by AlphaBeth** [comment]
Какие именно? build и out - это каталоги, созданные вашей IDE для хранения скомпилированных файлов. Каталог .idea - конфигурация проекта для Intellij IDEA. Первые два однозначно не нужны в репозитории, ибо они не несут ничего полезного для вашего проекта -- собрать можно и без них. 
Нужно ли опубликовывать в репозитории конфигурацию IDE -- вопрос спорный, верного ответа на него нет. Я считаю, что не стоит.

**Comment by skychik** [comment]
На данный момент не понятно, как удалить это все на гитхабе. В процессе..

**Comment by skychik** [comment]
Вроде как решил. Если нет, пишите
